/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/entrance.ts" />
/// <reference path="../scenes/leftpath/leftpath.ts" />
/// <reference path="../scenes/leftpath/farleft.ts" />
/// <reference path="../scenes/leftpath/leftmiddle.ts" />
/// <reference path="../scenes/rightpath/rightpath.ts" />
/// <reference path="../scenes/rightpath/farright.ts" />
/// <reference path="../scenes/rightpath/rightmiddle.ts" />
/// <reference path="../scenes/endings/badending1.ts" />
/// <reference path="../scenes/endings/badending2.ts" />
/// <reference path="../scenes/endings/badending3.ts" />
/// <reference path="../scenes/endings/badending4.ts" />
/// <reference path="../scenes/endings/badending5.ts" />
/// <reference path="../scenes/endings/badending6.ts" />
/// <reference path="../scenes/endings/badending7.ts" />
/// <reference path="../scenes/endings/goodending.ts" />
//# sourceMappingURL=_reference.js.map